version: '3.8'

services:
  mongo_db:
    container_name: database
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - "27017:27017"
  
  app:
    build: .
    container_name: nest_app
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb://mongo_db:27017/InVozo
      - EMAIL_ADDRESS=${EMAIL_ADDRESS}
      - EMAIL_PASSWORD=${EMAIL_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - mongo_db
    command: npm run start:dev

volumes:
  mongo_db:
